// @ts-nocheck
import { useState, useCallback, useMemo } from "react";
import {
  vipScoreFromMatch,
  pickBestSelectionForMatch,
} from "@/utils/matchUtils";
import useBetslipStore, { getRealOdds } from "@/store/betslipStore";

export function useAutoPickLogic({
  user,
  maxMatches,
  getMatchCount,
  rawMatches,
  hasKickoffPassed,
  isMatchInBetslip,
  addMatch,
  selectors,
}) {
  const [autoRange, setAutoRange] = useState("today");
  const [autoCustomRange, setAutoCustomRange] = useState({
    startDate: "",
    endDate: "",
  });
  const [autoSelectedLeagues, setAutoSelectedLeagues] = useState([]);
  const [autoStyle, setAutoStyle] = useState("safe");
  const [autoCount, setAutoCount] = useState(5);
  const [autoTargetOdds, setAutoTargetOdds] = useState(5.0);

  const [autoTimeWindow, setAutoTimeWindow] = useState("all");
  const [autoDiversify, setAutoDiversify] = useState(false);
  const [autoBlacklist, setAutoBlacklist] = useState("");
  
  const [autoGeneratedTitle, setAutoGeneratedTitle] = useState("");

  
  const [autoMarkets, setAutoMarkets] = useState({
    all: true,
    m1x2: true,
    doubleChance: true,
    overUnder: true,
    btts: true,
    correctScore: false,
    haOverUnder15: false,
    comboPicks: false, // Phase 1
  });
  
  const [autoTargetMode, setAutoTargetMode] = useState("count"); // "count", "odds", "odds_builder"
  const [autoStreak, setAutoStreak] = useState(false); // Phase 4
  const [autoExcludeCups, setAutoExcludeCups] = useState(false); // Phase 5


  const [auto1x2Options, setAuto1x2Options] = useState({
    home: true,
    draw: false,
    away: true,
  });

  const [autoDoubleChanceOptions, setAutoDoubleChanceOptions] = useState({
    homeDraw: true,
    homeAway: true,
    drawAway: true,
  });

  const [autoOUOptions, setAutoOUOptions] = useState({
    selections: [{ type: "over", line: 2.5 }],
  });

  const [autoBTTSOptions, setAutoBTTSOptions] = useState({
    yes: true,
    no: false,
  });

  // New state for H/A O/U 1.5 options
  const [autoHAOU15Options, setAutoHAOU15Options] = useState({
    homeOver: true,
    homeUnder: false,
    awayOver: true,
    awayUnder: false,
  });

  const [autoPreview, setAutoPreview] = useState([]);

  const pad2 = (n) => String(n).padStart(2, "0");
  const toISODate = (d) =>
    `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())}`;
  const todayISO = useMemo(() => toISODate(new Date()), []);
  const tomorrowISO = useMemo(() => {
    const d = new Date();
    d.setDate(d.getDate() + 1);
    return toISODate(d);
  }, []);

  const getCurrentWeekRange = useCallback(() => {
    const now = new Date();
    const day = now.getDay();
    const diffToMonday = day === 0 ? -6 : 1 - day;

    const monday = new Date(now);
    monday.setDate(now.getDate() + diffToMonday);
    monday.setHours(0, 0, 0, 0);

    const sunday = new Date(monday);
    sunday.setDate(monday.getDate() + 6);
    sunday.setHours(23, 59, 59, 999);

    return { monday, sunday };
  }, []);

  const { monday, sunday } = useMemo(getCurrentWeekRange, [
    getCurrentWeekRange,
  ]);

  const isInCurrentWeek = useCallback(
    (iso) => {
      if (!iso) return false;
      const d = new Date(iso + "T00:00:00");
      return d >= monday && d <= sunday;
    },
    [monday, sunday],
  );

  const passesAutoRange = useCallback(
    (m) => {
      const iso = selectors.getISODate(m);
      if (!iso) return false;

      if (autoRange === "today") return iso === todayISO;
      if (autoRange === "tomorrow") return iso === tomorrowISO;
      if (autoRange === "week") return isInCurrentWeek(iso);

      if (autoRange === "manual") {
        const start = String(autoCustomRange?.startDate || "").trim();
        const end = String(autoCustomRange?.endDate || "").trim();

        if (!start && !end) return true;

        if (start && iso < start) return false;
        if (end && iso > end) return false;

        return true;
      }

      const start = new Date(todayISO + "T00:00:00");
      const end = new Date(start);

      if (autoRange === "next3") {
        end.setDate(start.getDate() + 2);
      } else if (autoRange === "next7") {
        end.setDate(start.getDate() + 6);
      } else {
        return true;
      }

      const d = new Date(iso + "T00:00:00");
      return d >= start && d <= end;
    },
    [
      autoRange,
      autoCustomRange,
      selectors,
      todayISO,
      tomorrowISO,
      isInCurrentWeek,
    ],
  );

  const passesTimeWindow = useCallback(
    (m) => {
      if (autoTimeWindow === "all") return true;
      const t = selectors.getTime(m); // e.g. "14:30"
      if (!t) return false;
      const hr = parseInt(t.split(":")[0], 10);
      if (isNaN(hr)) return true;

      if (autoTimeWindow === "morning") return hr >= 6 && hr < 12;
      if (autoTimeWindow === "afternoon") return hr >= 12 && hr < 17;
      if (autoTimeWindow === "evening") return hr >= 17 && hr <= 23;
      if (autoTimeWindow === "next4h") {
        const now = new Date();
        const mTime = new Date();
        mTime.setHours(hr, parseInt(t.split(":")[1], 10), 0, 0);
        const diffHr = (mTime - now) / (1000 * 60 * 60);
        return diffHr >= 0 && diffHr <= 4;
      }
      return true;
    },
    [autoTimeWindow, selectors]
  );

  const passesBlacklist = useCallback(
    (m) => {
      if (!autoBlacklist.trim()) return true;
      const terms = autoBlacklist.toLowerCase().split(",").map((s) => s.trim()).filter(Boolean);
      if (terms.length === 0) return true;
      const mStr = `${m?.home} ${m?.away} ${m?.league} ${m?.fullLeague}`.toLowerCase();
      return !terms.some((t) => mStr.includes(t));
    },
    [autoBlacklist]
  );

  const passesAutoLeague = useCallback(
    (m) => {
      if (!autoSelectedLeagues?.length) return true;

      const selected = autoSelectedLeagues.map((l) =>
        String(l || "")
          .trim()
          .toLowerCase(),
      );

      const fullLeague = String(m?.fullLeague || "")
        .trim()
        .toLowerCase();
      const shortLeague = String(m?.league || "")
        .trim()
        .toLowerCase();

      return selected.includes(fullLeague) || selected.includes(shortLeague);
    },
    [autoSelectedLeagues],
  );

  const vipScoreOf = useCallback(
    (m) => {
      const c = selectors.getChance(m);
      const r = selectors.getRating(m);
      return Math.round(c * 0.6 + r * 0.4);
    },
    [selectors],
  );

  
  const stylePass = useCallback(
    (m) => {
      // Phase 3: Expected Value (EV) filter
      if (autoStyle === "ev") {
        // Just need >0 probability and >1.0 odds to calc EV
        return true; 
      }
      
      const c = selectors.getChance(m);
      const r = selectors.getRating(m);
      const flag = selectors.getFlag(m) === "✅";

      if (autoStyle === "safe") return flag && c >= 75 && r >= 70;
      if (autoStyle === "balanced")
        return (flag && c >= 70) || (c >= 72 && r >= 65);
      return flag || (c >= 65 && r >= 60);
    },
    [autoStyle, selectors],
  );


  const generateAutoPreview = useCallback(() => {
    if (!user) {
      alert("Sign in to use Auto Pick.");
      return;
    }

    const capacity = (maxMatches || 20) - getMatchCount();
    const target = Math.max(0, Math.min(autoCount, capacity));

    if (target <= 0) {
      alert(`BetSlip is full. Max ${maxMatches || 20} matches allowed.`);
      return;
    }

    const candidates = rawMatches
      .filter((m) => !hasKickoffPassed(m))
      .filter((m) => !isMatchInBetslip(m?.match))
      .filter(passesAutoRange)
      .filter(passesTimeWindow)
      .filter(passesAutoLeague)
      
      .filter(passesBlacklist)
      .filter(m => {
         // Phase 5: Exclude High Volatility (Cups/Derbies)
         if (autoExcludeCups) {
           const l = (m.league || "") + " " + (m.fullLeague || "");
           const vol = ["cup", "copa", "pokal", "efl", "fa", "coppa", "trophy", "supercopa"];
           if (vol.some(v => l.toLowerCase().includes(v))) return false;
         }
         // Phase 4: Streaks (Require W or D in last 2)
         if (autoStreak) {
           const hR = String(m.hRecent || "").toUpperCase();
           const aR = String(m.aRecent || "").toUpperCase();
           // Example: "W L W" -> we check if they have at least one W in recent
           if (!hR.includes("W") && !aR.includes("W")) return false;
         }
         return true;
      })
      .filter(stylePass)

      
    // Sort logic
    candidates.sort((a, b) => {
      if (autoStyle === "ev") {
        // For EV we just sort by raw chance as a proxy, real EV calculated inside the loop
        return selectors.getChance(b) - selectors.getChance(a);
      }
      return vipScoreOf(b) - vipScoreOf(a);
    });

    const preview = [];
    let currentOdds = 1.0;
    const leagueCounts = {};

    // PHASE 2: Target Optimizer (Combinatorics for exact odds)
    if (autoTargetMode === "odds_builder") {
       // We want to find a combination of matches that perfectly hits autoTargetOdds (e.g. 2.00)
       // We'll run a quick recursive DFS on the top 15 candidates
       const topCands = candidates.slice(0, 20);
       let bestCombo = [];
       let bestDiff = 999;
       
       const dfs = (idx, currentSel, currOdds) => {
         if (currOdds >= autoTargetOdds) {
           const diff = currOdds - autoTargetOdds;
           if (diff < bestDiff) {
             bestDiff = diff;
             bestCombo = [...currentSel];
           }
           return;
         }
         if (currentSel.length >= capacity) return;
         if (idx >= topCands.length) return;
         
         const m = topCands[idx];
         const sel = pickBestSelectionForMatch(m, autoStyle, { autoMarkets, auto1x2Options, autoOUOptions, autoBTTSOptions, autoDoubleChanceOptions, autoHAOU15Options });
         if (sel?.selectedMarket) {
           const realOdds = getRealOdds(m, sel.selectedMarket, sel.selectedOption);
           if (realOdds > 1.0) {
             let ev = (sel.prob / 100) * realOdds - 1;
             currentSel.push({ ...m, selectedMarket: sel.selectedMarket, selectedOption: sel.selectedOption, prob: sel.prob, odds: realOdds, ev });
             dfs(idx + 1, currentSel, currOdds * realOdds);
             currentSel.pop();
           }
         }
         dfs(idx + 1, currentSel, currOdds); // skip
       };
       
       dfs(0, [], 1.0);
       
       for (const match of bestCombo) {
          // Phase 6: AI Narrative
          let aiReasoning = `Algorithmic match optimized for the ${autoTargetOdds}x Target Builder.`;
          if (autoStyle === "ev" && match.ev > 0) aiReasoning = `Value Bet Detected! Bookmakers mispriced a ${Math.round(match.prob)}% statistical probability.`;
          else if (match.selectedMarket === "Combo") aiReasoning = `AI bundled uncorrelated markets to boost odds safely.`;
          
          preview.push({ ...match, aiReasoning });
       }
       
       setAutoPreview(preview);
       setAutoGeneratedTitle(`AI Target Builder (${autoTargetOdds}x)`);
       return;
    }

    // Normal Greedy Loop
    for (const m of candidates) {
      if (autoTargetMode === "count" && preview.length >= target) break;
      if (autoTargetMode === "odds" && currentOdds >= autoTargetOdds) break;

      const sel = pickBestSelectionForMatch(m, autoStyle, {
        autoMarkets,
        auto1x2Options,
        autoOUOptions,
        autoBTTSOptions,
        autoDoubleChanceOptions,
        autoHAOU15Options,
      });

      if (!sel?.selectedMarket) continue;
      
      const realOdds = getRealOdds(m, sel.selectedMarket, sel.selectedOption);
      if (!realOdds || realOdds <= 1) continue;
      
      const prob = sel.prob || sel.bestProb || 0;
      const matchOdds = realOdds;

      // Phase 3: Value Bet EV check
      const ev = (prob / 100) * matchOdds - 1;
      if (autoStyle === "ev" && ev < 0.02) continue; // Only accept bets with +2% edge in EV mode

      // Smart Diversification: Cap at 2 matches per league
      if (autoDiversify) {
        const l = m.league || m.fullLeague || "unknown";
        if ((leagueCounts[l] || 0) >= 2) continue;
        leagueCounts[l] = (leagueCounts[l] || 0) + 1;
      }

      // In Odds mode, don't exceed max matches capacity
      if (preview.length >= capacity) break;

      currentOdds *= matchOdds;

      // Phase 6: AI Narrative
      let aiReasoning = `Statistically safe pick with ${Math.round(prob)}% confidence.`;
      if (autoStyle === "ev") aiReasoning = `Value Bet: Positive Expected Value (+${(ev*100).toFixed(1)}% Edge).`;
      else if (sel.selectedMarket === "Combo") aiReasoning = `Combo Pick: Juiced odds by combining safely correlated markets.`;
      else if (autoStreak) aiReasoning = `Momentum Pick: Team is currently riding a strong positive streak.`;

      preview.push({
        ...m,
        selectedMarket: sel.selectedMarket,
        selectedOption: sel.selectedOption,
        prob: prob,
        odds: matchOdds,
        ev: ev,
        aiReasoning
      });
      
      if (autoTargetMode === "odds" && currentOdds >= autoTargetOdds) break; // slightly overshoot
    }


    setAutoPreview(preview);
    
    // AI Slip Naming (Procedural)
    if (preview.length > 0) {
      const themes = ["The Acca Builder", "Midnight Express", "Value Seeker", "Weekend Banker", "The Underdog Punter", "Goal Fest", "Risk Taker"];
      const prefixes = ["Epic", "Cautious", "Aggressive", "Tactical", "Calculated", "Optimal", "Elite"];
      const randomPrefix = prefixes[Math.floor(Math.random() * prefixes.length)];
      const randomTheme = themes[Math.floor(Math.random() * themes.length)];
      setAutoGeneratedTitle(`${randomPrefix} ${randomTheme} (AI)`);
    } else {
      setAutoGeneratedTitle("");
    }
  }, [
    user,
    maxMatches,
    getMatchCount,
    autoCount,
    rawMatches,
    hasKickoffPassed,
    isMatchInBetslip,
    passesAutoRange,
    passesTimeWindow,
    passesAutoLeague,
    passesBlacklist,
    stylePass,
    vipScoreOf,
    autoStyle,
    autoMarkets,
    auto1x2Options,
    autoOUOptions,
    autoBTTSOptions,
    autoDoubleChanceOptions,
    autoHAOU15Options,
    autoTargetMode,
    autoTargetOdds,
    autoDiversify,
    autoExcludeCups,
    autoStreak,
  ]);

  const confirmAutoPick = useCallback(() => {
    let added = 0;

    for (const m of autoPreview) {
      const ok = addMatch(m);
      if (ok) added++;
    }

    if (autoGeneratedTitle) {
      useBetslipStore.getState().setSlipTitle(autoGeneratedTitle);
    }

    setAutoPreview([]);
    alert(`Auto Pick added ${added} match(es).`);
  }, [autoPreview, addMatch, autoGeneratedTitle]);

  return {
    autoRange,
    setAutoRange,
    autoCustomRange,
    setAutoCustomRange,
    autoSelectedLeagues,
    setAutoSelectedLeagues,
    autoStyle,
    setAutoStyle,
    autoCount,
    setAutoCount,
    autoMarkets,
    setAutoMarkets,
    auto1x2Options,
    setAuto1x2Options,
    autoOUOptions,
    setAutoOUOptions,
    autoBTTSOptions,
    setAutoBTTSOptions,
    autoDoubleChanceOptions,
    setAutoDoubleChanceOptions,
    autoHAOU15Options, // Export new state
    setAutoHAOU15Options, // Export setter
    autoPreview,
    setAutoPreview,
    generateAutoPreview,
    confirmAutoPick,
    autoTimeWindow,
    setAutoTimeWindow,
    autoDiversify,
    setAutoDiversify,
    autoBlacklist,
    setAutoBlacklist,
    autoTargetMode,
    setAutoTargetMode,
    autoTargetOdds,
    setAutoTargetOdds,
    autoGeneratedTitle,
    autoStreak,
    setAutoStreak,
    autoExcludeCups,
    setAutoExcludeCups,
  };
}
